# Generated by Django 4.2.3 on 2023-08-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='slug',
        ),
    ]
